# docker-compose.yml
services:
  baseball-scouting-app:
    build: .
    container_name: baseball-scouting-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - baseball-network
    depends_on:
      - nginx-proxy-manager

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"  # Admin interface
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
    networks:
      - baseball-network

networks:
  baseball-network:
    driver: bridge

